/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

/**
 *
 * @author x15007707
 */
public class OneGuessGUI extends javax.swing.JFrame {

    /**
     * Creates new form OneGuessGUI
     */
    public OneGuessGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captionLbl = new javax.swing.JLabel();
        oneLbl = new javax.swing.JLabel();
        twoLbl = new javax.swing.JLabel();
        threeLbl = new javax.swing.JLabel();
        fourLbl = new javax.swing.JLabel();
        fiveLbl = new javax.swing.JLabel();
        twoTxt = new javax.swing.JTextField();
        oneTxt = new javax.swing.JTextField();
        threeTxt = new javax.swing.JTextField();
        fourTxt = new javax.swing.JTextField();
        fiveTxt = new javax.swing.JTextField();
        submitLbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        resultsLbl = new javax.swing.JLabel();
        otherGamesFrame = new javax.swing.JInternalFrame();
        otherGamesLbl = new javax.swing.JLabel();
        twoTrialBtn = new javax.swing.JButton();
        threeTrialBtn = new javax.swing.JButton();
        danyGameLbl = new javax.swing.JLabel();
        danyGameBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        captionLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        captionLbl.setForeground(new java.awt.Color(255, 255, 204));
        captionLbl.setText("Please enter your five special digits below!");
        getContentPane().add(captionLbl);
        captionLbl.setBounds(89, 131, 453, 29);

        oneLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneLbl.setForeground(new java.awt.Color(255, 255, 255));
        oneLbl.setText("Digit 1");
        getContentPane().add(oneLbl);
        oneLbl.setBounds(117, 198, 39, 17);

        twoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoLbl.setForeground(new java.awt.Color(255, 255, 255));
        twoLbl.setText("Digit 2");
        getContentPane().add(twoLbl);
        twoLbl.setBounds(117, 224, 39, 17);

        threeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threeLbl.setForeground(new java.awt.Color(255, 255, 255));
        threeLbl.setText("Digit 3");
        getContentPane().add(threeLbl);
        threeLbl.setBounds(117, 247, 39, 17);

        fourLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fourLbl.setForeground(new java.awt.Color(255, 255, 255));
        fourLbl.setText("Digit 4");
        getContentPane().add(fourLbl);
        fourLbl.setBounds(117, 270, 39, 17);

        fiveLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fiveLbl.setForeground(new java.awt.Color(255, 255, 255));
        fiveLbl.setText("Digit 5");
        getContentPane().add(fiveLbl);
        fiveLbl.setBounds(117, 294, 39, 17);

        twoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(twoTxt);
        twoTxt.setBounds(196, 220, 29, 21);

        oneTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(oneTxt);
        oneTxt.setBounds(196, 197, 29, 21);

        threeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(threeTxt);
        threeTxt.setBounds(196, 243, 29, 21);

        fourTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(fourTxt);
        fourTxt.setBounds(196, 266, 29, 21);

        fiveTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(fiveTxt);
        fiveTxt.setBounds(196, 293, 29, 21);

        submitLbl.setText("Send my guess!");
        getContentPane().add(submitLbl);
        submitLbl.setBounds(224, 363, 76, 14);

        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(209, 383, 105, 37);

        resultsLbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(255, 204, 204));
        resultsLbl.setText(" ");
        getContentPane().add(resultsLbl);
        resultsLbl.setBounds(10, 530, 690, 58);

        otherGamesFrame.setVisible(true);
        otherGamesFrame.getContentPane().setLayout(null);

        otherGamesLbl.setText("You may also try the games with :");
        otherGamesFrame.getContentPane().add(otherGamesLbl);
        otherGamesLbl.setBounds(32, 11, 163, 14);

        twoTrialBtn.setText("2 Trials");
        twoTrialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoTrialBtnActionPerformed(evt);
            }
        });
        otherGamesFrame.getContentPane().add(twoTrialBtn);
        twoTrialBtn.setBounds(88, 58, 67, 23);

        threeTrialBtn.setText("3 Trials");
        threeTrialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeTrialBtnActionPerformed(evt);
            }
        });
        otherGamesFrame.getContentPane().add(threeTrialBtn);
        threeTrialBtn.setBounds(88, 92, 67, 23);

        danyGameLbl.setText("Or alternatively,");
        otherGamesFrame.getContentPane().add(danyGameLbl);
        danyGameLbl.setBounds(32, 160, 79, 14);

        danyGameBtn.setText("Lotto, Plus 1 and Plus 2 Game");
        danyGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danyGameBtnActionPerformed(evt);
            }
        });
        otherGamesFrame.getContentPane().add(danyGameBtn);
        danyGameBtn.setBounds(20, 192, 175, 23);

        getContentPane().add(otherGamesFrame);
        otherGamesFrame.setBounds(420, 180, 247, 319);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/background.jpg"))); // NOI18N
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void twoTrialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoTrialBtnActionPerformed
        // TODO add your handling code here:
        TwoGuessGUI myGuess = new TwoGuessGUI();
        myGuess.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_twoTrialBtnActionPerformed

    private void threeTrialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeTrialBtnActionPerformed
        // TODO add your handling code here:
        ThreeGuessGUI myGuess = new ThreeGuessGUI();
        myGuess.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_threeTrialBtnActionPerformed

    private void danyGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danyGameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danyGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneGuessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneGuessGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel captionLbl;
    private javax.swing.JButton danyGameBtn;
    private javax.swing.JLabel danyGameLbl;
    private javax.swing.JLabel fiveLbl;
    private javax.swing.JTextField fiveTxt;
    private javax.swing.JLabel fourLbl;
    private javax.swing.JTextField fourTxt;
    private javax.swing.JLabel oneLbl;
    private javax.swing.JTextField oneTxt;
    private javax.swing.JInternalFrame otherGamesFrame;
    private javax.swing.JLabel otherGamesLbl;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel submitLbl;
    private javax.swing.JLabel threeLbl;
    private javax.swing.JButton threeTrialBtn;
    private javax.swing.JTextField threeTxt;
    private javax.swing.JLabel twoLbl;
    private javax.swing.JButton twoTrialBtn;
    private javax.swing.JTextField twoTxt;
    // End of variables declaration//GEN-END:variables
}
